### ISSUE TITLE
Add / fix support for code 25 interleaved (ITF-14)

### ISSUE THREAD

**Issue by eternaldb** [myflashlab/barcode-ANE#36]
when scanning the barcode we need with another app, it says it is a code 25 interleaved.  When I look that up it says it is also known as a ITF14 which you say the ANE supports and it scans the example on your page.  Without being able to scan this type we can't use your ANE (which we bought).  Any help would be greatly appreciated.  I included an example.
![50594422102__71540c99-058b-4e20-9bd4-0e0b266a4d19](https://cloud.githubusercontent.com/assets/3949576/21908704/6c7f9f60-d8da-11e6-995d-76ff0f3e9377.JPG)

**Comment by myflashlab** [comment]
We tested this on Android, and it says it's a ```ITF14``` with the correct number shown. On the iOS side however, it is not detecting the barcode at all. It seems like to be a native bug or something. Unfortunaitly there is nothing we can do about this because the detection part is happening on the official iOS frameworks by apple. They are not detecting it to begin with. While I have to close the issue because we cannot think of any solution for this, below are some tips that might worth a shot.

* try to use another barcode format on your tickets.
* post the screenshot on stackoverflow and ask native iOS programmers if they are able to scan it successfully with the iOS scan framework?
